// bedrock_service.proto — unified grpc schema for music aggregation.
// normalizes fields from spotify, yandex, vk, deezer, soundcloud, youtube.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: bedrock_service.proto

package bedrock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BedrockService_SearchTracks_FullMethodName        = "/bedrock.BedrockService/SearchTracks"
	BedrockService_SearchAlbums_FullMethodName        = "/bedrock.BedrockService/SearchAlbums"
	BedrockService_SearchArtists_FullMethodName       = "/bedrock.BedrockService/SearchArtists"
	BedrockService_SearchPlaylists_FullMethodName     = "/bedrock.BedrockService/SearchPlaylists"
	BedrockService_GetTrack_FullMethodName            = "/bedrock.BedrockService/GetTrack"
	BedrockService_GetAlbum_FullMethodName            = "/bedrock.BedrockService/GetAlbum"
	BedrockService_GetArtist_FullMethodName           = "/bedrock.BedrockService/GetArtist"
	BedrockService_GetPlaylist_FullMethodName         = "/bedrock.BedrockService/GetPlaylist"
	BedrockService_GetStreamURL_FullMethodName        = "/bedrock.BedrockService/GetStreamURL"
	BedrockService_GetSimilarTracks_FullMethodName    = "/bedrock.BedrockService/GetSimilarTracks"
	BedrockService_GetLyrics_FullMethodName           = "/bedrock.BedrockService/GetLyrics"
	BedrockService_GetAnnotations_FullMethodName      = "/bedrock.BedrockService/GetAnnotations"
	BedrockService_RecordPlay_FullMethodName          = "/bedrock.BedrockService/RecordPlay"
	BedrockService_GetListeningHistory_FullMethodName = "/bedrock.BedrockService/GetListeningHistory"
	BedrockService_GetPopularTracks_FullMethodName    = "/bedrock.BedrockService/GetPopularTracks"
	BedrockService_GetPopularArtists_FullMethodName   = "/bedrock.BedrockService/GetPopularArtists"
	BedrockService_ImportPlaylist_FullMethodName      = "/bedrock.BedrockService/ImportPlaylist"
	BedrockService_GetServiceStatus_FullMethodName    = "/bedrock.BedrockService/GetServiceStatus"
	BedrockService_Register_FullMethodName            = "/bedrock.BedrockService/Register"
	BedrockService_Login_FullMethodName               = "/bedrock.BedrockService/Login"
	BedrockService_RefreshToken_FullMethodName        = "/bedrock.BedrockService/RefreshToken"
)

// BedrockServiceClient is the client API for BedrockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service definition
type BedrockServiceClient interface {
	// search: fans out to all (or selected) platforms in parallel, merges results.
	// if one provider fails, STATUS_PARTIAL is returned with ProviderErrors.
	SearchTracks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error)
	SearchAlbums(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchAlbumsResponse, error)
	SearchArtists(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchArtistsResponse, error)
	SearchPlaylists(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchPlaylistsResponse, error)
	// get single item
	GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*GetTrackResponse, error)
	GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error)
	GetArtist(ctx context.Context, in *GetArtistRequest, opts ...grpc.CallOption) (*GetArtistResponse, error)
	GetPlaylist(ctx context.Context, in *GetPlaylistRequest, opts ...grpc.CallOption) (*GetPlaylistResponse, error)
	// stream: returns direct audio url, applies provider fallback logic (e.g. spotify -> soundcloud -> vk).
	GetStreamURL(ctx context.Context, in *GetStreamURLRequest, opts ...grpc.CallOption) (*GetStreamURLResponse, error)
	// recommendations
	GetSimilarTracks(ctx context.Context, in *GetSimilarTracksRequest, opts ...grpc.CallOption) (*GetSimilarTracksResponse, error)
	// lyrics: fetches from lrclib (synced) and/or genius (plain-text) in parallel, returns best match. mirrors python get_track_lyrics() fan-out.
	GetLyrics(ctx context.Context, in *LyricsRequest, opts ...grpc.CallOption) (*LyricsResponse, error)
	// annotations: returns genius community annotations for a song, each anchored to a lyric fragment.
	GetAnnotations(ctx context.Context, in *AnnotationsRequest, opts ...grpc.CallOption) (*AnnotationsResponse, error)
	// listening statistics: record play event (call after user has streamed track). uses redis dedup (5 min window) to avoid double-counting.
	RecordPlay(ctx context.Context, in *RecordPlayRequest, opts ...grpc.CallOption) (*RecordPlayResponse, error)
	// retrieve personal listening history for authenticated user.
	GetListeningHistory(ctx context.Context, in *ListeningHistoryRequest, opts ...grpc.CallOption) (*ListeningHistoryResponse, error)
	// charts: aggregate play counts across all users. metadata enriched in parallel with 3s per-track timeout (mirrors python get_popular_tracks logic).
	GetPopularTracks(ctx context.Context, in *PopularRequest, opts ...grpc.CallOption) (*PopularTracksResponse, error)
	GetPopularArtists(ctx context.Context, in *PopularRequest, opts ...grpc.CallOption) (*PopularArtistsResponse, error)
	// playlist import: resolves public playlist url from any supported platform, returns full ordered track listing. 120s timeout internally.
	ImportPlaylist(ctx context.Context, in *ImportPlaylistRequest, opts ...grpc.CallOption) (*ImportPlaylistResponse, error)
	// health / observability: returns live or cached health probes for every downstream dependency (platforms, lyrics providers, auth). mirrors python get /metrics/status.
	GetServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error)
	// authentication
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
}

type bedrockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBedrockServiceClient(cc grpc.ClientConnInterface) BedrockServiceClient {
	return &bedrockServiceClient{cc}
}

func (c *bedrockServiceClient) SearchTracks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTracksResponse)
	err := c.cc.Invoke(ctx, BedrockService_SearchTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) SearchAlbums(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchAlbumsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAlbumsResponse)
	err := c.cc.Invoke(ctx, BedrockService_SearchAlbums_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) SearchArtists(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchArtistsResponse)
	err := c.cc.Invoke(ctx, BedrockService_SearchArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) SearchPlaylists(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlaylistsResponse)
	err := c.cc.Invoke(ctx, BedrockService_SearchPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetTrack(ctx context.Context, in *GetTrackRequest, opts ...grpc.CallOption) (*GetTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...grpc.CallOption) (*GetAlbumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlbumResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetAlbum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetArtist(ctx context.Context, in *GetArtistRequest, opts ...grpc.CallOption) (*GetArtistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtistResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetPlaylist(ctx context.Context, in *GetPlaylistRequest, opts ...grpc.CallOption) (*GetPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetStreamURL(ctx context.Context, in *GetStreamURLRequest, opts ...grpc.CallOption) (*GetStreamURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamURLResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetStreamURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetSimilarTracks(ctx context.Context, in *GetSimilarTracksRequest, opts ...grpc.CallOption) (*GetSimilarTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimilarTracksResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetSimilarTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetLyrics(ctx context.Context, in *LyricsRequest, opts ...grpc.CallOption) (*LyricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LyricsResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetLyrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetAnnotations(ctx context.Context, in *AnnotationsRequest, opts ...grpc.CallOption) (*AnnotationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnotationsResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetAnnotations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) RecordPlay(ctx context.Context, in *RecordPlayRequest, opts ...grpc.CallOption) (*RecordPlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordPlayResponse)
	err := c.cc.Invoke(ctx, BedrockService_RecordPlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetListeningHistory(ctx context.Context, in *ListeningHistoryRequest, opts ...grpc.CallOption) (*ListeningHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListeningHistoryResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetListeningHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetPopularTracks(ctx context.Context, in *PopularRequest, opts ...grpc.CallOption) (*PopularTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PopularTracksResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetPopularTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetPopularArtists(ctx context.Context, in *PopularRequest, opts ...grpc.CallOption) (*PopularArtistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PopularArtistsResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetPopularArtists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) ImportPlaylist(ctx context.Context, in *ImportPlaylistRequest, opts ...grpc.CallOption) (*ImportPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportPlaylistResponse)
	err := c.cc.Invoke(ctx, BedrockService_ImportPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) GetServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatusResponse)
	err := c.cc.Invoke(ctx, BedrockService_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, BedrockService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, BedrockService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bedrockServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, BedrockService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BedrockServiceServer is the server API for BedrockService service.
// All implementations must embed UnimplementedBedrockServiceServer
// for forward compatibility.
//
// service definition
type BedrockServiceServer interface {
	// search: fans out to all (or selected) platforms in parallel, merges results.
	// if one provider fails, STATUS_PARTIAL is returned with ProviderErrors.
	SearchTracks(context.Context, *SearchRequest) (*SearchTracksResponse, error)
	SearchAlbums(context.Context, *SearchRequest) (*SearchAlbumsResponse, error)
	SearchArtists(context.Context, *SearchRequest) (*SearchArtistsResponse, error)
	SearchPlaylists(context.Context, *SearchRequest) (*SearchPlaylistsResponse, error)
	// get single item
	GetTrack(context.Context, *GetTrackRequest) (*GetTrackResponse, error)
	GetAlbum(context.Context, *GetAlbumRequest) (*GetAlbumResponse, error)
	GetArtist(context.Context, *GetArtistRequest) (*GetArtistResponse, error)
	GetPlaylist(context.Context, *GetPlaylistRequest) (*GetPlaylistResponse, error)
	// stream: returns direct audio url, applies provider fallback logic (e.g. spotify -> soundcloud -> vk).
	GetStreamURL(context.Context, *GetStreamURLRequest) (*GetStreamURLResponse, error)
	// recommendations
	GetSimilarTracks(context.Context, *GetSimilarTracksRequest) (*GetSimilarTracksResponse, error)
	// lyrics: fetches from lrclib (synced) and/or genius (plain-text) in parallel, returns best match. mirrors python get_track_lyrics() fan-out.
	GetLyrics(context.Context, *LyricsRequest) (*LyricsResponse, error)
	// annotations: returns genius community annotations for a song, each anchored to a lyric fragment.
	GetAnnotations(context.Context, *AnnotationsRequest) (*AnnotationsResponse, error)
	// listening statistics: record play event (call after user has streamed track). uses redis dedup (5 min window) to avoid double-counting.
	RecordPlay(context.Context, *RecordPlayRequest) (*RecordPlayResponse, error)
	// retrieve personal listening history for authenticated user.
	GetListeningHistory(context.Context, *ListeningHistoryRequest) (*ListeningHistoryResponse, error)
	// charts: aggregate play counts across all users. metadata enriched in parallel with 3s per-track timeout (mirrors python get_popular_tracks logic).
	GetPopularTracks(context.Context, *PopularRequest) (*PopularTracksResponse, error)
	GetPopularArtists(context.Context, *PopularRequest) (*PopularArtistsResponse, error)
	// playlist import: resolves public playlist url from any supported platform, returns full ordered track listing. 120s timeout internally.
	ImportPlaylist(context.Context, *ImportPlaylistRequest) (*ImportPlaylistResponse, error)
	// health / observability: returns live or cached health probes for every downstream dependency (platforms, lyrics providers, auth). mirrors python get /metrics/status.
	GetServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error)
	// authentication
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	mustEmbedUnimplementedBedrockServiceServer()
}

// UnimplementedBedrockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBedrockServiceServer struct{}

func (UnimplementedBedrockServiceServer) SearchTracks(context.Context, *SearchRequest) (*SearchTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTracks not implemented")
}
func (UnimplementedBedrockServiceServer) SearchAlbums(context.Context, *SearchRequest) (*SearchAlbumsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAlbums not implemented")
}
func (UnimplementedBedrockServiceServer) SearchArtists(context.Context, *SearchRequest) (*SearchArtistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchArtists not implemented")
}
func (UnimplementedBedrockServiceServer) SearchPlaylists(context.Context, *SearchRequest) (*SearchPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPlaylists not implemented")
}
func (UnimplementedBedrockServiceServer) GetTrack(context.Context, *GetTrackRequest) (*GetTrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrack not implemented")
}
func (UnimplementedBedrockServiceServer) GetAlbum(context.Context, *GetAlbumRequest) (*GetAlbumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlbum not implemented")
}
func (UnimplementedBedrockServiceServer) GetArtist(context.Context, *GetArtistRequest) (*GetArtistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtist not implemented")
}
func (UnimplementedBedrockServiceServer) GetPlaylist(context.Context, *GetPlaylistRequest) (*GetPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylist not implemented")
}
func (UnimplementedBedrockServiceServer) GetStreamURL(context.Context, *GetStreamURLRequest) (*GetStreamURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamURL not implemented")
}
func (UnimplementedBedrockServiceServer) GetSimilarTracks(context.Context, *GetSimilarTracksRequest) (*GetSimilarTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimilarTracks not implemented")
}
func (UnimplementedBedrockServiceServer) GetLyrics(context.Context, *LyricsRequest) (*LyricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLyrics not implemented")
}
func (UnimplementedBedrockServiceServer) GetAnnotations(context.Context, *AnnotationsRequest) (*AnnotationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnnotations not implemented")
}
func (UnimplementedBedrockServiceServer) RecordPlay(context.Context, *RecordPlayRequest) (*RecordPlayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordPlay not implemented")
}
func (UnimplementedBedrockServiceServer) GetListeningHistory(context.Context, *ListeningHistoryRequest) (*ListeningHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListeningHistory not implemented")
}
func (UnimplementedBedrockServiceServer) GetPopularTracks(context.Context, *PopularRequest) (*PopularTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularTracks not implemented")
}
func (UnimplementedBedrockServiceServer) GetPopularArtists(context.Context, *PopularRequest) (*PopularArtistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularArtists not implemented")
}
func (UnimplementedBedrockServiceServer) ImportPlaylist(context.Context, *ImportPlaylistRequest) (*ImportPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportPlaylist not implemented")
}
func (UnimplementedBedrockServiceServer) GetServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedBedrockServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedBedrockServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBedrockServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedBedrockServiceServer) mustEmbedUnimplementedBedrockServiceServer() {}
func (UnimplementedBedrockServiceServer) testEmbeddedByValue()                        {}

// UnsafeBedrockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BedrockServiceServer will
// result in compilation errors.
type UnsafeBedrockServiceServer interface {
	mustEmbedUnimplementedBedrockServiceServer()
}

func RegisterBedrockServiceServer(s grpc.ServiceRegistrar, srv BedrockServiceServer) {
	// If the following call panics, it indicates UnimplementedBedrockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BedrockService_ServiceDesc, srv)
}

func _BedrockService_SearchTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).SearchTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_SearchTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).SearchTracks(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_SearchAlbums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).SearchAlbums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_SearchAlbums_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).SearchAlbums(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_SearchArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).SearchArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_SearchArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).SearchArtists(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_SearchPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).SearchPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_SearchPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).SearchPlaylists(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetTrack(ctx, req.(*GetTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetAlbum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetAlbum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetAlbum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetAlbum(ctx, req.(*GetAlbumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetArtist(ctx, req.(*GetArtistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetPlaylist(ctx, req.(*GetPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetStreamURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetStreamURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetStreamURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetStreamURL(ctx, req.(*GetStreamURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetSimilarTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetSimilarTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetSimilarTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetSimilarTracks(ctx, req.(*GetSimilarTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetLyrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LyricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetLyrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetLyrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetLyrics(ctx, req.(*LyricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetAnnotations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetAnnotations(ctx, req.(*AnnotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_RecordPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).RecordPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_RecordPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).RecordPlay(ctx, req.(*RecordPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetListeningHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListeningHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetListeningHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetListeningHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetListeningHistory(ctx, req.(*ListeningHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetPopularTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopularRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetPopularTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetPopularTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetPopularTracks(ctx, req.(*PopularRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetPopularArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopularRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetPopularArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetPopularArtists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetPopularArtists(ctx, req.(*PopularRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_ImportPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).ImportPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_ImportPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).ImportPlaylist(ctx, req.(*ImportPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).GetServiceStatus(ctx, req.(*ServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BedrockService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BedrockServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BedrockService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BedrockServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BedrockService_ServiceDesc is the grpc.ServiceDesc for BedrockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BedrockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bedrock.BedrockService",
	HandlerType: (*BedrockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTracks",
			Handler:    _BedrockService_SearchTracks_Handler,
		},
		{
			MethodName: "SearchAlbums",
			Handler:    _BedrockService_SearchAlbums_Handler,
		},
		{
			MethodName: "SearchArtists",
			Handler:    _BedrockService_SearchArtists_Handler,
		},
		{
			MethodName: "SearchPlaylists",
			Handler:    _BedrockService_SearchPlaylists_Handler,
		},
		{
			MethodName: "GetTrack",
			Handler:    _BedrockService_GetTrack_Handler,
		},
		{
			MethodName: "GetAlbum",
			Handler:    _BedrockService_GetAlbum_Handler,
		},
		{
			MethodName: "GetArtist",
			Handler:    _BedrockService_GetArtist_Handler,
		},
		{
			MethodName: "GetPlaylist",
			Handler:    _BedrockService_GetPlaylist_Handler,
		},
		{
			MethodName: "GetStreamURL",
			Handler:    _BedrockService_GetStreamURL_Handler,
		},
		{
			MethodName: "GetSimilarTracks",
			Handler:    _BedrockService_GetSimilarTracks_Handler,
		},
		{
			MethodName: "GetLyrics",
			Handler:    _BedrockService_GetLyrics_Handler,
		},
		{
			MethodName: "GetAnnotations",
			Handler:    _BedrockService_GetAnnotations_Handler,
		},
		{
			MethodName: "RecordPlay",
			Handler:    _BedrockService_RecordPlay_Handler,
		},
		{
			MethodName: "GetListeningHistory",
			Handler:    _BedrockService_GetListeningHistory_Handler,
		},
		{
			MethodName: "GetPopularTracks",
			Handler:    _BedrockService_GetPopularTracks_Handler,
		},
		{
			MethodName: "GetPopularArtists",
			Handler:    _BedrockService_GetPopularArtists_Handler,
		},
		{
			MethodName: "ImportPlaylist",
			Handler:    _BedrockService_ImportPlaylist_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _BedrockService_GetServiceStatus_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _BedrockService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _BedrockService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _BedrockService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bedrock_service.proto",
}
