package models

import "time"

// user represents a user record in the authentication system.
type User struct {
	// id is the unique identifier (uuid) generated by the database.
	ID string `json:"id" db:"id"`

	// email is the unique email address of the user.
	Email string `json:"email" db:"email"`

	// password_hash stores the securely hashed password (e.g., bcrypt/argon2).
	// it's not exposed in json responses.
	PasswordHash string `json:"-" db:"password_hash"`

	// role defines the authorization level (default 'user').
	Role string `json:"role" db:"role"`

	// is_verified indicates if the user has verified their email address.
	IsVerified bool `json:"is_verified" db:"is_verified"`

	// created_at is the timestamp when the user was created.
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}
